spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]  # .env 공통 사용
  application:
    name: kotsu-example

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

cloud:
  aws:
    s3:
      bucket: kotsubucket
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}