spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}  # 예: jdbc:mysql://your-db.rds.amazonaws.com:3306/db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}  # 예: your-redis.cache.amazonaws.com
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

kakao:
  rest-api-key: ${REST_API_KEY}
  redirect-uri: ${REDIRECT_URI}
