spring:
  config:
    import: optional:file:.env[.properties]  # .env 공통 사용
  application:
    name: kotsu-example

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET}